### PR TITLE
fix https://github.com/wwyf/Waterfall-backend/issues/17

### PR DESCRIPTION
**Pull request by wwyf**

### CODE REVIEW

**Comment by wwyf** [comment]
Now, I make some change in API : `/apis/order/mainOrder` (get and post)
1. get: add login check
2. post: add login check and backend can get `createuser` from cookies, so frontend does not need to pass `createuser`.

**Comment by wwyf** [comment]
Notice that only customer can add new mainOrder.

**Comment by wwyf** [comment]
But the test failed.
```
=================================== FAILURES ===================================
___________________ test_add_new_main_order[json_body0-res0] ___________________
json_body = {'address': 'None', 'comments': 'None', 'createuser': '1', 'deadline': datetime.datetime(2019, 5, 28, 7, 14, 47, 605920), ...}
res = {'code': 0, 'id': 0, 'msg': '提交成功'}
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f5c36978ac8>
    @pytest.mark.parametrize('json_body, res', param_add_new_main_order)
    def test_add_new_main_order(json_body, res, monkeypatch):
        def mock_db_add(order):
            order.ID = 0
    
        def mock_db_commit():
            return
    
        with monkeypatch.context() as m:
            monkeypatch.setattr("src.api.mainorder_api.db.session",
                                Mocker(add=mock_db_add, commit=mock_db_commit))
>           result = add_new_main_order(json_body)
tests/api/test_mainorder_api.py:119: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/api/mainorder_api.py:73: in add_new_main_order
    if not (session.get('username') and session['role'] == 'customer'):
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/werkzeug/local.py:348: in __getattr__
    return getattr(self._get_current_object(), name)
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/werkzeug/local.py:307: in _get_current_object
    return self.__local()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
name = 'session'
    def _lookup_req_object(name):
        top = _request_ctx_stack.top
        if top is None:
>           raise RuntimeError(_request_ctx_err_msg)
E           RuntimeError: Working outside of request context.
E           
E           This typically means that you attempted to use functionality that needed
E           an active HTTP request.  Consult the documentation on testing for
E           information about how to avoid this problem.
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/flask/globals.py:37: RuntimeError


```

**Comment by YanB25** [comment]
Have you figured out why the error occurs? Or you understand the error, but fail to fix it ?

**Comment by wwyf** [comment]
fix it.

**Pull request merged**
